name: Deploy Sail to DigitalOcean

on: 
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
       - name: Checkout Code
        uses: actions/checkout@v3

        - name: Setup Php
         uses: shivammathur/setup-php@v2
         with:
          php-version: 8.4

        - name: Install Composer Deps
         run: composer install --optimize-autoloader --no-dev --no-progress --no-interaction --prefer-dist

        - name: Install Node
         uses: actions/setup-node@v3
         with:
         node-version: '22'

        - name: Install npm deps
         run: npm run build

        - name: Sync files with server
         uses: easingthemes/ssh-deploy@v2.1.5
         env:
            SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
            SOURCE: "."
            REMOTE_HOST: ${{ secrets.VPS_HOST }}
            REMOTE_USER: ${{ secrets.VPS_USER }}
            TARGET: "/home/laravel/paysoko-app.test"

        - name: Run Remote Cmd
         uses: appleboy/ssh-action@v0.1.6
         with:
            host: ${{ secrets.VPS_HOST }}
            username: ${{ secrets.VPS_USER }}
            key: ${{ secrets.SSH_PRIVATE_KEY }}
            script: |
              cd /home/laravel/paysoko-app.test
              sail artisan migrate --force
              sail artisan optimize